import Head from "next/head";

import { Suspense, useState } from "react";
import { Canvas } from "@react-three/fiber";
import { Environment, Scroll, ScrollControls } from "@react-three/drei";
import { Intro } from "@/components/Intro/Intro";
import { LoadingScreen } from "@/components/LoadingScreen";
import { HtmlContent } from "@/components/HtmlContent/HtmlContent";

export default function Home() {
  const [isLoading, setIsLoading] = useState(true);

  return (
    <>
      <Head>
        <title>Leonardo Maglio 3D Resume</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main
        style={{
          display: "flex",
          justifyContent: "center",
          alignItems: "center",
          height: "100vh",
          width: "100vw",
          background: "#e2b6ff",
        }}
      >
        <LoadingScreen isLoading={isLoading} setIsLoading={setIsLoading} />
        <Suspense fallback={null}>
          <Canvas
            shadows
            dpr={[1, 2]}
            camera={{ position: [16, 10, 30], fov: 42 }}
          >
            <Environment preset="lobby" />
            <ScrollControls pages={4} damping={0.1}>
              <Scroll html>
                <HtmlContent />
              </Scroll>
              <Scroll>
                <Intro />
              </Scroll>
            </ScrollControls>
          </Canvas>
        </Suspense>
      </main>
    </>
  );
}
